version: '3.2'
services:
    ide:
        build: 
            context: .
            args:
                USER: ${X_USER}
                GROUP: ${X_GROUP}
                UID: ${X_UID}
                GID: ${X_GID}
                GOPATH: ${X_GOPATH}
                PROJECT_DIR: ${PROJECT_DIR}
                PROJECT_NS: ${PROJECT_NS}
                PROJECT_NAME: ${PROJECT_NAME}
                USER_PWD: ${USER_PWD}
                ROOT_PWD: ${ROOT_PWD}
        image: arris/secql
        ports: 
            - "3000:3000"
        security_opt:
            - seccomp:unconfined
        volumes:
            - ${PROJECT_DIR}:/opt/code/src/${PROJECT_NS}
