version: '3'
services:
    ide:
        build: 
            context: .
            args:
                USER: ${X_USER}
                GROUP: ${X_GROUP}
                UID: ${X_UID}
                GID: ${X_GID}
                USER_PWD: ${USER_PWD}
                ROOT_PWD: ${ROOT_PWD}
                CODE_DIR: ${CODE_DIR}
                PROJECT_DIR: ${PROJECT_DIR}
        environment:
            DISPLAY: ${X_DISPLAY}
        image: arris/vscode
        ports: 
            - "3000:3000"
        userns_mode: "host"
        user: "${X_UID}:${X_GID}"
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ~/Code:${CODE_DIR}
