
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/acroca/go-symbols"

[[constraint]]
  name = "github.com/cweill/gotests"
  version = "1.5.2"

[[constraint]]
  name = "github.com/derekparker/delve"
  version = "0.12.2"

[[constraint]]
  branch = "master"
  name = "github.com/fatih/gomodifytags"

[[constraint]]
  branch = "master"
  name = "github.com/golang/lint"

[[constraint]]
  branch = "master"
  name = "github.com/josharian/impl"

[[constraint]]
  branch = "master"
  name = "github.com/nsf/gocode"

[[constraint]]
  branch = "master"
  name = "github.com/ramya-rao-a/go-outline"

[[constraint]]
  branch = "master"
  name = "github.com/rogpeppe/godef"

[[constraint]]
  branch = "master"
  name = "github.com/uudashr/gopkgs"

[[constraint]]
  branch = "master"
  name = "github.com/zmb3/gogetdoc"

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"

[[constraint]]
  branch = "master"
  name = "github.com/sqs/goreturns"
